### Register a new user
POST http://localhost:8000/api/v1/auth/register
content-type: application/json

{
    "username": "mrchidex",
    "email":"mrchidex@email.com",
    "password":"1234"
}

### Signin a new user
POST http://localhost:8000/api/v1/auth/login
content-type: application/json

{
    "username": "mrchidex",
    "email":"mrchidex@email.com",
    "password":"1234"
}