### Register a new user
POST http://localhost:8000/api/v1/auth/register
content-type: application/json

{
    "username": "mrchidex",
    "email":"mrchidex@email.com",
    "password":"1234"
}

### Signin a new user
POST http://localhost:8000/api/v1/auth/login
content-type: application/json

{
    "username": "mrchidex",
    "email":"mrchidex@email.com",
    "password":"1234"
}

### Get all users
GET http://localhost:8000/api/v1/users

### update a user
PATCH http://localhost:8000/api/v1/auth/users
content-type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njc4NTU3NDE1MTksImlzcyI6Ik1yLUNoaWRleCIsInVzZXJuYW1lIjoibXJjaGlkZXgiLCJlbWFpbCI6Im1yY2hpZGV4QGVtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJwcm9maWxlUGljIjpudWxsLCJjb3ZlclBpYyI6bnVsbCwiZXhwIjoxNjY3ODU1OTE0MzE5fQ.7vRI9Qo_D2s7aQoYzXuvYLemY99TUz7SONGaxyoMNqw"

{
    "username": "mrchidex",
    "email":"mrchidex@email.com",
}